### ISSUE TITLE
Make package importable

### ISSUE THREAD

**Issue by fredr** [robpike/hira#3]
It would be awesome if this package (and kata and kana) was importable as 3rd party packages. If you agree I can open some PRs.

E.g the command can be moved to /cmd/hira/hira.go

**Comment by robpike** [comment]
A good idea, but let me do the work to avoid licensing issues.

**Comment by fredr** [comment]
Sure! 

PS. If it's the CLA you are thinking about, I have one of those.

**Comment by robpike** [comment]
Done. See also github.com/robpike/nihongo.

**Comment by fredr** [comment]
Sweet! :beers:
